import type { Rule, RiskLevel } from "./domain";
const specs: [string, string, string, number, number, RiskLevel, string][] = [
  [
    "R001",
    "High balance depletion",
    "LIQUIDITY",
    20,
    0.9,
    "HIGH",
    "Outgoing amount and fee consume at least 90% of balance.",
  ],
  [
    "R002",
    "Critical balance depletion",
    "LIQUIDITY",
    35,
    0.97,
    "CRITICAL",
    "Outgoing amount and fee consume at least 97% of balance.",
  ],
  [
    "R003",
    "Failed PIN attempts",
    "CREDENTIAL",
    15,
    3,
    "MEDIUM",
    "Repeated unsuccessful PIN attempts.",
  ],
  [
    "R004",
    "OTP resend surge",
    "CREDENTIAL",
    10,
    3,
    "MEDIUM",
    "Repeated OTP resend requests.",
  ],
  [
    "R005",
    "Recent PIN reset",
    "CREDENTIAL",
    15,
    1,
    "MEDIUM",
    "PIN was recently reset.",
  ],
  [
    "R006",
    "New device",
    "DEVICE",
    10,
    1,
    "MEDIUM",
    "Unrecognized device fingerprint.",
  ],
  [
    "R007",
    "New device with high amount",
    "DEVICE",
    25,
    20000,
    "HIGH",
    "High-value outgoing transaction from a new device.",
  ],
  [
    "R008",
    "Rooted device",
    "DEVICE",
    15,
    1,
    "HIGH",
    "Compromised runtime integrity.",
  ],
  [
    "R009",
    "Emulator detected",
    "DEVICE",
    20,
    1,
    "HIGH",
    "Transaction originates from an emulator.",
  ],
  [
    "R010",
    "VPN active",
    "DEVICE",
    8,
    1,
    "MEDIUM",
    "Network origin is obscured.",
  ],
  [
    "R011",
    "Transaction velocity",
    "BEHAVIOR",
    20,
    5,
    "HIGH",
    "More than five transactions in a five-minute window, including this attempt.",
  ],
  [
    "R012",
    "Rapid fund turnaround",
    "LIQUIDITY",
    25,
    120,
    "HIGH",
    "Outgoing funds follow a recent cash-in within 120 seconds.",
  ],
  [
    "R013",
    "Channel hopping",
    "BEHAVIOR",
    15,
    300,
    "MEDIUM",
    "Channel changed within five minutes or is flagged by context.",
  ],
  [
    "R014",
    "Balance inquiry surge",
    "BEHAVIOR",
    15,
    3,
    "MEDIUM",
    "Repeated balance inquiries precede an outgoing transfer.",
  ],
  [
    "R015",
    "Impossible travel",
    "LOCATION",
    40,
    900,
    "CRITICAL",
    "Location implies travel faster than 900 km/h.",
  ],
  [
    "R016",
    "High-risk recipient",
    "TOPOLOGY",
    25,
    70,
    "HIGH",
    "Recipient risk is derived from sender concentration and prior fraud decisions.",
  ],
  [
    "R017",
    "Blacklisted device",
    "BLOCKLIST",
    100,
    1,
    "CRITICAL",
    "Hard reject for a device on the server-managed blocklist.",
  ],
  [
    "R018",
    "Blacklisted agent",
    "BLOCKLIST",
    100,
    1,
    "CRITICAL",
    "Hard reject for an agent on the server-managed blocklist.",
  ],
];
export function defaultRules(): Rule[] {
  return specs.map(
    ([code, name, category, weight, threshold, severity, description]) => ({
      code,
      name,
      category,
      weight,
      threshold,
      severity,
      description,
      enabled: true,
      version: 1,
      updated_at: "2026-10-01T00:00:00.000Z",
    }),
  );
}
